---
name: Aide CI Linux

on: [push]

jobs:
  build:
    name: "${{ matrix.compiler }} compiler"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y meson bison flex nettle-dev libpcre2-dev zlib1g-dev check clang
      - name: Configure
        run: meson setup builddir
        env:
          CC: ${{ matrix.compiler }}
      - name: Build
        run: meson compile -C builddir -v
      - name: Test
        run: meson test -C builddir --verbose
