---
name: AIDE CI macOS

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install meson bison libgcrypt libgpg-error pcre2 check
      - name: update path
        run: echo /opt/homebrew/opt/bison/bin >> ${GITHUB_PATH}
      - name: Configure
        run: meson setup builddir
        env:
          CC: ${{ matrix.compiler }}
      - name: Build
        run: meson compile -C builddir
      - name: Test
        run: meson test -C builddir
